module.exports = {
  players: [
    { name: 'pid', label: '玩家ID', type: 'number' },
    { name: 'name', label: '昵称', type: 'text' },
    { name: 'hp', label: '生命值', type: 'number' },
    { name: 'sp', label: '体力', type: 'number' },
    { name: 'pls', label: '所在区域', type: 'number' },
    { name: 'money', label: '金钱', type: 'number' },
    { name: 'state', label: '状态', type: 'number' },
  ],
  npcs: [
    { name: 'pid', label: 'NPCID', type: 'number' },
    { name: 'name', label: '名字', type: 'text' },
    {
      name: 'spawnStage',
      label: '生成时机',
      type: 'select',
      options: ['start', 'ban2', 'ban4'],
    },
    { name: 'hp', label: '生命值', type: 'number' },
    { name: 'mhp', label: '最大生命', type: 'number' },
    { name: 'sp', label: '体力', type: 'number' },
    { name: 'msp', label: '最大体力', type: 'number' },
    { name: 'att', label: '攻击力', type: 'number' },
    { name: 'def', label: '防御力', type: 'number' },
    { name: 'pls', label: '所在区域', type: 'number' },
    { name: 'state', label: '状态', type: 'number' },
    { name: 'wep', label: '武器名', type: 'text' },
    { name: 'wepk', label: '武器种类', type: 'text' },
    { name: 'wepe', label: '武器效果', type: 'number' },
    { name: 'weps', label: '武器耐久', type: 'text' },
    { name: 'wepsk', label: '武器属性', type: 'text' },
    { name: 'arb', label: '身体防具名', type: 'text' },
    { name: 'arbk', label: '身体防具种类', type: 'text' },
    { name: 'arbe', label: '身体防具效果', type: 'number' },
    { name: 'arbs', label: '身体防具耐久', type: 'text' },
    { name: 'arbsk', label: '身体防具属性', type: 'text' },
    { name: 'arh', label: '头部防具名', type: 'text' },
    { name: 'arhk', label: '头部防具种类', type: 'text' },
    { name: 'arhe', label: '头部防具效果', type: 'number' },
    { name: 'arhs', label: '头部防具耐久', type: 'text' },
    { name: 'arhsk', label: '头部防具属性', type: 'text' },
    { name: 'ara', label: '腕部防具名', type: 'text' },
    { name: 'arak', label: '腕部防具种类', type: 'text' },
    { name: 'arae', label: '腕部防具效果', type: 'number' },
    { name: 'aras', label: '腕部防具耐久', type: 'text' },
    { name: 'arask', label: '腕部防具属性', type: 'text' },
    { name: 'arf', label: '足部防具名', type: 'text' },
    { name: 'arfk', label: '足部防具种类', type: 'text' },
    { name: 'arfe', label: '足部防具效果', type: 'number' },
    { name: 'arfs', label: '足部防具耐久', type: 'text' },
    { name: 'arfsk', label: '足部防具属性', type: 'text' },
    { name: 'art', label: '饰品名', type: 'text' },
    { name: 'artk', label: '饰品种类', type: 'text' },
    { name: 'arte', label: '饰品效果', type: 'number' },
    { name: 'arts', label: '饰品耐久', type: 'text' },
    { name: 'artsk', label: '饰品属性', type: 'text' },
    { name: 'itm0', label: '道具1', type: 'text' },
    { name: 'itmk0', label: '道具1种类', type: 'text' },
    { name: 'itme0', label: '道具1效果', type: 'number' },
    { name: 'itms0', label: '道具1耐久', type: 'text' },
    { name: 'itmsk0', label: '道具1属性', type: 'text' },
    { name: 'itm1', label: '道具2', type: 'text' },
    { name: 'itmk1', label: '道具2种类', type: 'text' },
    { name: 'itme1', label: '道具2效果', type: 'number' },
    { name: 'itms1', label: '道具2耐久', type: 'text' },
    { name: 'itmsk1', label: '道具2属性', type: 'text' },
    { name: 'itm2', label: '道具3', type: 'text' },
    { name: 'itmk2', label: '道具3种类', type: 'text' },
    { name: 'itme2', label: '道具3效果', type: 'number' },
    { name: 'itms2', label: '道具3耐久', type: 'text' },
    { name: 'itmsk2', label: '道具3属性', type: 'text' },
    { name: 'itm3', label: '道具4', type: 'text' },
    { name: 'itmk3', label: '道具4种类', type: 'text' },
    { name: 'itme3', label: '道具4效果', type: 'number' },
    { name: 'itms3', label: '道具4耐久', type: 'text' },
    { name: 'itmsk3', label: '道具4属性', type: 'text' },
    { name: 'itm4', label: '道具5', type: 'text' },
    { name: 'itmk4', label: '道具5种类', type: 'text' },
    { name: 'itme4', label: '道具5效果', type: 'number' },
    { name: 'itms4', label: '道具5耐久', type: 'text' },
    { name: 'itmsk4', label: '道具5属性', type: 'text' },
    { name: 'itm5', label: '道具6', type: 'text' },
    { name: 'itmk5', label: '道具6种类', type: 'text' },
    { name: 'itme5', label: '道具6效果', type: 'number' },
    { name: 'itms5', label: '道具6耐久', type: 'text' },
    { name: 'itmsk5', label: '道具6属性', type: 'text' },
    { name: 'itm6', label: '道具7', type: 'text' },
    { name: 'itmk6', label: '道具7种类', type: 'text' },
    { name: 'itme6', label: '道具7效果', type: 'number' },
    { name: 'itms6', label: '道具7耐久', type: 'text' },
    { name: 'itmsk6', label: '道具7属性', type: 'text' },
  ],
  shopitems: [
    { name: 'sid', label: '物品ID', type: 'number' },
    { name: 'item', label: '名称', type: 'text' },
    { name: 'price', label: '价格', type: 'number' },
    { name: 'area', label: '地区', type: 'number' },
  ],
  items: [
    { name: 'name', label: '名称', type: 'text' },
    { name: 'kind', label: '种类', type: 'text' },
    { name: 'effect', label: '效果值', type: 'number' },
    { name: 'dur', label: '耐久/数量', type: 'text' },
    { name: 'skill', label: '属性', type: 'text' },
  ],
  users: [
    { name: 'username', label: '用户名', type: 'text' },
    { name: 'role', label: '角色', type: 'select', options: ['user', 'admin'] },
  ],
  logs: [
    { name: 'lid', label: '日志ID', type: 'number' },
    { name: 'time', label: '时间戳', type: 'number' },
    { name: 'log', label: '日志内容', type: 'text' },
  ],
  chats: [
    { name: 'cid', label: '聊天ID', type: 'number' },
    {
      name: 'type',
      label: '频道',
      type: 'select',
      options: ['0', '1', '2', '3'],
    },
    { name: 'name', label: '发送者', type: 'text' },
    { name: 'msg', label: '内容', type: 'text' },
    { name: 'time', label: '时间戳', type: 'number' },
  ],
  mapitems: [
    {
      name: 'stage',
      label: '刷新阶段',
      type: 'select',
      options: ['start', 'ban2', 'ban4'],
    },
    { name: 'itm', label: '道具名', type: 'text' },
    { name: 'itmk', label: '种类', type: 'text' },
    { name: 'itme', label: '效果值', type: 'number' },
    { name: 'itms', label: '次数/耐久', type: 'text' },
    { name: 'itmsk', label: '属性', type: 'text' },
    { name: 'pls', label: '所在区域', type: 'number' },
  ],
  maptraps: [
    { name: 'itm', label: '陷阱名', type: 'text' },
    { name: 'itmk', label: '类型', type: 'text' },
    { name: 'itme', label: '伤害', type: 'number' },
    { name: 'itms', label: '用途/次数', type: 'text' },
    { name: 'pls', label: '布设区域', type: 'number' },
  ],
  mapareas: [
    { name: 'pid', label: '区域ID', type: 'number' },
    { name: 'name', label: '区域名', type: 'text' },
    { name: 'danger', label: '危险度', type: 'number' },
  ],
  newsinfos: [
    { name: 'nid', label: '新闻ID', type: 'number' },
    { name: 'news', label: '内容', type: 'text' },
    { name: 'time', label: '时间戳', type: 'number' },
  ],
  roomlisteners: [
    { name: 'port', label: '端口', type: 'number' },
    {
      name: 'status',
      label: '状态',
      type: 'select',
      options: ['监听中', '已关闭'],
    },
  ],
  histories: [
    { name: 'gid', label: '游戏ID', type: 'number' },
    { name: 'winner', label: '胜利者', type: 'text' },
    { name: 'winmode', label: '胜利方式', type: 'number' },
    { name: 'endtime', label: '结束时间戳', type: 'number' },
  ],
  gameinfos: [
    { name: 'version', label: '版本', type: 'text' },
    { name: 'gamenum', label: '局数', type: 'number' },
    { name: 'gametype', label: '模式', type: 'number' },
    {
      name: 'gamestate',
      label: '状态',
      type: 'select',
      options: ['未开始', '进行中', '已结束'],
    },
    { name: 'groomid', label: '房间ID', type: 'number' },
    { name: 'groomtype', label: '房间类型', type: 'number' },
    { name: 'groomstatus', label: '房间状态', type: 'number' },
    { name: 'starttime', label: '开始时间', type: 'number' },
    { name: 'afktime', label: '离线时间', type: 'number' },
    { name: 'validnum', label: '有效人数', type: 'number' },
    { name: 'alivenum', label: '存活人数', type: 'number' },
    { name: 'deathnum', label: '死亡数', type: 'number' },
    { name: 'combonum', label: '连杀数', type: 'number' },
    { name: 'weather', label: '天气', type: 'number' },
    { name: 'hack', label: '禁区解除', type: 'number' },
    { name: 'hdamage', label: '最高伤害', type: 'number' },
    { name: 'hplayer', label: '伤害玩家', type: 'text' },
    { name: 'winmode', label: '胜利模式', type: 'number' },
    { name: 'winner', label: '胜利者', type: 'text' },
    { name: 'areanum', label: '已有禁区数', type: 'number' },
    { name: 'areatime', label: '禁区时间', type: 'number' },
    { name: 'areawarn', label: '禁区警告', type: 'number' },
    { name: 'arealist', label: '禁区列表', type: 'text' },
    { name: 'noisevars', label: '噪音参数', type: 'text' },
    { name: 'roomvars', label: '房间变量', type: 'text' },
    { name: 'gamevars', label: '游戏变量', type: 'text' },
  ],
  itemcategories: [
    { name: 'name', label: '类别名称', type: 'text' },
    {
      name: 'type',
      label: '类别类型',
      type: 'select',
      options: ['mapitem', 'maptrap'],
    },
    { name: 'area', label: '区域ID', type: 'number' },
    {
      name: 'tables',
      label: '使用刷新表',
      type: 'multiselect',
      options: ['mapitem', 'mapitem_i8', 'mapitem_i9'],
    },
  ],
  npcspawns: [
    { name: 'npc', label: 'NPC名', type: 'select', options: [] },
    { name: 'num', label: '数量', type: 'number' },
    {
      name: 'stage',
      label: '刷新阶段',
      type: 'select',
      options: ['start', 'ban2', 'ban4'],
    },
  ],
  maps: [
    { name: 'pls', label: '区域ID', type: 'number' },
    { name: 'name', label: '区域名', type: 'text' },
    { name: 'players', label: '玩家列表', type: 'text' },
  ],
};
